/**
 * /api/market — Market Prices + Trend Prediction
 * All data generated by Groq API — location-aware, season-aware, date-aware.
 * No hardcoded prices, no hardcoded crops, no hardcoded insights.
 */
'use strict';
const express = require('express');
const router  = express.Router();
const Groq    = require('groq-sdk');

const client = new Groq({ apiKey: process.env.GROQ_API_KEY });

// ─── Helper: call Groq and parse JSON safely ──────────────────────────────────
async function groqJSON(prompt, maxTokens = 1500) {
  const completion = await client.chat.completions.create({
    model:       process.env.GROQ_MODEL,
    max_tokens:  maxTokens,
    temperature: 0.2,
    messages: [{ role: 'user', content: prompt }],
  });
  const raw     = completion.choices[0]?.message?.content || '';
  const cleaned = raw.replace(/```json|```/gi, '').trim();
  return JSON.parse(cleaned);
}

// ─── Current season helper ────────────────────────────────────────────────────
function getCurrentSeason() {
  const month = new Date().getMonth() + 1; // 1–12
  if (month >= 6  && month <= 9)  return 'Kharif (Monsoon)';
  if (month >= 10 && month <= 11) return 'Kharif Harvest';
  if (month === 12 || month <= 3) return 'Rabi (Winter)';
  return 'Rabi Harvest / Zaid';
}

// ─── Build prompt for mandi prices ───────────────────────────────────────────
function buildPricesPrompt(category, district, state) {
  const now       = new Date();
  const dateStr   = now.toLocaleDateString('en-IN', { day: 'numeric', month: 'long', year: 'numeric' });
  const season    = getCurrentSeason();
  const catFilter = category && category !== 'all'
    ? `Only include commodities from the category: "${category}" (grain | oilseed | vegetable | cash).`
    : `Include commodities actually grown and traded in ${district}, ${state} — do NOT list crops that are not relevant to this region.`;

  return `You are an expert on Indian agricultural mandi prices with deep knowledge of regional crop patterns.

Today's date: ${dateStr}
Current season: ${season}
Location: ${district} APMC, ${state}, India

Task: Generate realistic TODAY's mandi prices for crops that are actually grown and traded in ${district}, ${state}.
${catFilter}
Return 8–10 commodities.

Location-awareness rules:
- ONLY include crops that farmers in ${district}, ${state} actually grow this season.
- Examples by state (apply this logic for ${state}):
    Punjab / Haryana    → wheat, paddy, mustard, potato, sugarcane, maize
    Rajasthan           → bajra, moth bean, guar seed, mustard, cumin, jowar
    Maharashtra         → soybean, cotton, onion, jowar, tur dal, grapes
    Uttar Pradesh       → wheat, sugarcane, paddy, potato, mustard, arhar
    Gujarat             → groundnut, cotton, castor seed, cumin, bajra, wheat
    Madhya Pradesh      → soybean, wheat, gram, lentil, mustard, maize
    Karnataka           → ragi, jowar, sunflower, arhar, cotton, maize
    Andhra / Telangana  → paddy, cotton, maize, groundnut, chilli, turmeric
    Tamil Nadu          → paddy, banana, tapioca, groundnut, sugarcane, coconut
    Kerala              → coconut, rubber, banana, tapioca, black pepper, ginger
    West Bengal         → paddy, jute, potato, mustard, vegetables
    Bihar               → paddy, wheat, maize, lentil, mustard, vegetables
- Prices must reflect current market rates at ${district} mandi as of ${dateStr}.
- Adjust for seasonal supply: harvest season = lower prices; off-season = higher.

Respond ONLY with a valid JSON array — no markdown, no preamble, no explanation:

[
  {
    "commodity": "Wheat",
    "modal": 2200,
    "min": 2100,
    "max": 2350,
    "change": 45,
    "msp": 2275,
    "unit": "Quintal",
    "cat": "grain",
    "trend": "up",
    "code": "wheat"
  }
]

Field rules:
- "modal"  — most common traded price today at ${district} mandi (₹/Quintal)
- "min" / "max" — realistic range for today
- "change" — price change vs yesterday in ₹ (negative = price fell)
- "trend"  — "up" | "down" | "stable"
- "msp"    — Government of India MSP for 2024-25; null if no MSP exists for this crop
- "cat"    — "grain" | "oilseed" | "vegetable" | "cash"
- "code"   — lowercase snake_case identifier`;
}

// ─── Build prompt for insights ────────────────────────────────────────────────
function buildInsightsPrompt(district, state, prices) {
  const season  = getCurrentSeason();
  const summary = prices
    .map(p => `${p.commodity}: ₹${p.modal} (trend: ${p.trend}${p.msp ? ', MSP: ₹' + p.msp : ''})`)
    .join('\n');

  return `You are an agricultural market advisor helping farmers in ${district}, ${state}.

Season: ${season}
Today's mandi prices at ${district}:
${summary}

Generate exactly 3 short, actionable insights for local farmers based ONLY on the prices listed above.

Respond ONLY with a valid JSON array — no markdown, no explanation:

[
  { "type": "success", "text": "Insight here." }
]

Rules:
- "type": "success" (good opportunity) | "warning" (risk or caution) | "info" (useful tip)
- Each insight MUST reference a specific crop name and its price from the list above
- Maximum 15 words per insight
- Return exactly one of each type: success, warning, info`;
}

// ─── GET /api/market ──────────────────────────────────────────────────────────
router.get('/', async (req, res) => {
  const category = req.query.category || 'all';
  const district = (req.query.district || '').trim();
  const state    = (req.query.state    || '').trim();

  if (!district || !state) {
    return res.status(400).json({
      success: false,
      error:   true,
      code:    'MISSING_LOCATION',
      message: 'district and state query params are required.',
    });
  }

  try {
    // Step 1: fetch location-specific prices
    const prices = await groqJSON(buildPricesPrompt(category, district, state), 1500);

    // Step 2: fetch insights grounded in the actual prices returned
    let insights;
    try {
      insights = await groqJSON(buildInsightsPrompt(district, state, prices), 500);
    } catch {
      insights = [{ type: 'info', text: 'Visit eNAM portal for live prices across all mandis.' }];
    }

    return res.json({
      success:   true,
      mandi:     `${district} Agricultural Produce Market Committee`,
      state,
      district,
      season:    getCurrentSeason(),
      prices,
      mlEngine:  'groq-api',
      insights,
      updatedAt: new Date().toISOString(),
    });

  } catch (err) {
    console.error('Market API error:', err);

    if (err.status === 401) {
      return res.status(500).json({ success: false, error: true, code: 'AUTH_ERROR',  message: 'Groq API key invalid.' });
    }
    if (err.status === 429) {
      return res.status(429).json({ success: false, error: true, code: 'RATE_LIMIT',  message: 'Too many requests. Please wait a moment.' });
    }
    if (err instanceof SyntaxError) {
      return res.status(500).json({ success: false, error: true, code: 'PARSE_ERROR', message: 'AI response could not be parsed. Please try again.' });
    }

    return res.status(500).json({ success: false, error: true, message: err.message || 'Failed to fetch market prices.' });
  }
});

// ─── POST /api/market/predict-trend ──────────────────────────────────────────
router.post('/predict-trend', async (req, res) => {
  const { commodity, season, month, prevPrice, msp, district, state } = req.body;

  if (!commodity || !prevPrice) {
    return res.status(400).json({ success: false, message: 'commodity and prevPrice are required.' });
  }

  try {
    const now    = new Date();
    const prompt = `You are an agricultural price analyst for Indian markets.

Predict the 7-day price trend for this crop:

Commodity:     ${commodity}
Region:        ${district || ''}${district && state ? ', ' : ''}${state || 'India'}
Season:        ${season || getCurrentSeason()}
Month:         ${month || now.getMonth() + 1}
Current Price: ₹${prevPrice}/Quintal
MSP:           ${msp ? '₹' + msp : 'N/A'}

Respond ONLY with a valid JSON object — no markdown, no explanation:

{
  "trend": "up|down|stable",
  "trendLabel": "Human-readable label e.g. 'Moderate Rise Expected'",
  "confidence": 0.85,
  "reasoning": "One sentence max.",
  "pklBacked": false
}`;

    const result = await groqJSON(prompt, 300);
    return res.json({ success: true, ...result });

  } catch (err) {
    console.error('Predict-trend error:', err);
    return res.status(500).json({ success: false, message: err.message || 'Prediction failed.' });
  }
});

module.exports = router;