const express = require('express');
const router = express.Router();

const SCHEMES = [
  { id: 'pmkisan', icon: '💰', name: 'PM-KISAN Samman Nidhi', amount: '₹6,000/year', category: 'Income Support', color: 'green', description: 'Direct income support to all landholding farmers in 3 installments of ₹2,000 each. Over 11 crore farmers enrolled.', eligibility: 'All small & marginal farmers with cultivable land', documents: ['Aadhaar Card', 'Land Records (Khasra)', 'Bank Account + IFSC'], portal: 'https://pmkisan.gov.in', helpline: '155261 / 011-23381092' },
  { id: 'pmfby', icon: '🛡️', name: 'PM Fasal Bima Yojana', amount: '1.5-5% Premium', category: 'Crop Insurance', color: 'blue', description: 'Comprehensive crop insurance against natural calamities, pests, and diseases. Covers pre-sowing to post-harvest losses.', eligibility: 'All farmers growing notified crops in notified areas', documents: ['Land Records', 'Aadhaar', 'Bank Passbook', 'Sowing Certificate'], portal: 'https://pmfby.gov.in', helpline: '14447 / 1800-180-1551' },
  { id: 'shc', icon: '🧪', name: 'Soil Health Card Scheme', amount: 'FREE', category: 'Soil Testing', color: 'brown', description: 'Free soil testing every 2 years. Personalized fertilizer recommendations for 6 crops based on actual soil analysis.', eligibility: 'All farmers — apply at nearest KVK or Soil Testing Lab', documents: ['Aadhaar Card', 'Farm location details'], portal: 'https://soilhealth.dac.gov.in', helpline: '1800-180-1551' },
  { id: 'kcc', icon: '💳', name: 'Kisan Credit Card (KCC)', amount: 'Up to ₹3 Lakh @ 4%', category: 'Agricultural Credit', color: 'orange', description: 'Short-term credit for crop production, post-harvest expenses, and maintenance of farm assets at subsidized 4% interest p.a.', eligibility: 'All farmers, tenant farmers, oral lessees, SHG members', documents: ['Aadhaar', 'Land Records / Lease Agreement', 'Passport Photo', 'Income Proof'], portal: 'https://nabard.org', helpline: '1800-180-1551' },
  { id: 'pmksy', icon: '💧', name: 'PM Krishi Sinchai Yojana', amount: '55-75% Subsidy', category: 'Irrigation', color: 'cyan', description: 'Subsidy on drip and sprinkler irrigation systems. "Har Khet Ko Paani" — connects every farm to a water source.', eligibility: 'Small/marginal farmers (55%), others (45%) on micro-irrigation', documents: ['Land Records', 'Aadhaar', 'Bank Account', 'Quotation from dealer'], portal: 'https://pmksy.gov.in', helpline: '1800-180-1551' },
  { id: 'enam', icon: '📱', name: 'eNAM — Online Mandi', amount: 'Better Prices', category: 'Market Access', color: 'purple', description: 'Online trading platform connecting 1000+ mandis across India. Sell directly to buyers nationwide without middlemen.', eligibility: 'All farmers with registered land in any APMC', documents: ['Aadhaar', 'Bank Account', 'Mobile Number'], portal: 'https://enam.gov.in', helpline: '1800-270-0224' },
];

router.get('/', (req, res) => res.json({ success: true, schemes: SCHEMES }));
module.exports = router;
