/**
 * PestDetection v4.2 — Auto-Crop Detection
 * Removed manual crop selection; AI now determines the crop from the image.
 */

import { useState, useCallback, useRef } from 'react';
import { useDropzone } from 'react-dropzone';
import { motion, AnimatePresence } from 'framer-motion';
import api from '../utils/api';
import toast from 'react-hot-toast';
import { useApp } from '../context/AppContext';
import { Camera, X, Loader2, AlertTriangle, CheckCircle2, Info, Leaf, Download } from 'lucide-react';
import { downloadPDF } from '../utils/reportUtils';

// Kept for PDF translation labels based on AI response
const CROPS = [
  { value:'wheat', label:'Wheat', hi:'गेहूं', pa:'ਕਣਕ', te:'గోధుమ', ta:'கோதுமை' },
  { value:'rice', label:'Rice', hi:'धान', pa:'ਝੋਨਾ', te:'వరి', ta:'நெல்' },
  { value:'maize', label:'Maize', hi:'मक्का', pa:'ਮੱਕੀ', te:'మొక్కజొన్న', ta:'ਮੱਕਾਚੋਲਮ' },
  { value:'cotton', label:'Cotton', hi:'कपास', pa:'ਕਪਾਹ', te:'పత్తి', ta:'பருத்தி' },
  { value:'mustard', label:'Mustard', hi:'सरसों', pa:'ਸਰ੍ਹੋਂ', te:'ఆవాలు', ta:'கடுகு' },
  { value:'sugarcane', label:'Sugarcane', hi:'गन्ना', pa:'ਗੰਨਾ', te:'చెరకు', ta:'கரும்பு' },
  { value:'soybean', label:'Soybean', hi:'सोयाबीन', pa:'ਸੋਇਆਬੀਨ', te:'సోయాబీన్', ta:'சோயாபீன்' },
  { value:'tomato', label:'Tomato', hi:'टमाटर', pa:'ਟਮਾਟਰ', te:'టమాట', ta:'தக்காளி' },
  { value:'onion', label:'Onion', hi:'प्याज', pa:'ਪਿਆਜ਼', te:'ఉల్లిపాయ', ta:'வெங்காயம்' },
  { value:'potato', label:'Potato', hi:'आलू', pa:'ਆਲੂ', te:'బంగాళాదుంప', ta:'உருளைக்கிழங்கு' },
  { value:'gram', label:'Chickpea', hi:'चना', pa:'ਛੋਲੇ', te:'శనగ', ta:'கொண்டைக்கடலை' },
  { value:'groundnut', label:'Groundnut', hi:'मूंगफली', pa:'ਮੂੰਗਫਲੀ', te:'వేరుశనగ', ta:'வேர்க்கடலை' },
  { value:'sunflower', label:'Sunflower', hi:'सूरजमुखी', pa:'ਸੂਰਜਮੁਖੀ', te:'పొద్దుతిరుగుడు', ta:'சூரியகாந்தி' },
  { value:'sorghum', label:'Sorghum', hi:'ज्वार', pa:'ਜਵਾਰ', te:'జొన్న', ta:'சோளம்' },
  { value:'barley', label:'Barley', hi:'जौ', pa:'ਜੌਂ', te:'యవలు', ta:'பார்லி' },
  { value:'chili', label:'Chili', hi:'मिर्च', pa:'ਮਿਰਚ', te:'మిర్చి', ta:'மிளகாய்' },
  { value:'brinjal', label:'Brinjal', hi:'बैंगन', pa:'ਬੈਂਗਣ', te:'వంకాయ', ta:'கத்தரிக்காய்' },
  { value:'cauliflower', label:'Cauliflower', hi:'फूलगोभी', pa:'ਫੁੱਲਗੋਭੀ', te:'కాలీఫ్లవర్', ta:'காலிஃப்ளவர்' },
  { value:'lentil', label:'Lentil', hi:'मसूर', pa:'ਮਸੂਰ', te:'మసూర్', ta:'மசூர்' },
  { value:'turmeric', label:'Turmeric', hi:'हल्दी', pa:'ਹਲਦੀ', te:'పసుపు', ta:'மஞ்சள்' },
];

const TX = {
  en:{
    title:'Pest & Disease Detection',subtitle:'Upload a crop photo — AI identifies pests/diseases & recommends treatment',
    uploadTitle:'Upload Crop Image',dragText:'Drag & drop crop photo here',tapText:'or tap to select from gallery',
    sizeText:'JPG / PNG / WEBP up to 5MB',orText:'OR',cameraBtn:'Open Camera',removeBtn:'Remove Image',
    symptomsLabel:'Describe Symptoms (optional)',
    symptomsPlaceholder:'e.g. Yellow patches on leaves, white powder, curled leaves...',
    analyzeBtn:'Detect Pest / Disease',analyzing:'AI Analyzing...',
    detected:'Detected',severity:'Severity',affects:'Affects',
    symptoms:'Symptoms',chemical:'Chemical Treatment',organic:'Organic Treatment',
    prevention:'Prevention',spreadRisk:'Spread Risk',nearestExpert:'Nearest Expert',
    callExpert:'Call Expert',downloadReport:'Download Report',downloading:'Generating PDF...',
    commonPests:'Common Pests This Season',low:'Low',moderate:'Moderate',high:'High',confidence:'Confidence',
    tipText:'Upload a crop photo or describe symptoms, then tap Detect to get AI-powered results.',
    reportTitle:'Pest & Disease Detection Report',reportDate:'Date',reportCrop:'Crop',
    reportSeverity:'Severity Level',reportConfidence:'AI Confidence',reportSymptoms:'Observed Symptoms',
    reportChemical:'Chemical Treatment',reportOrganic:'Organic / Bio Treatment',
    reportPrevention:'Prevention Measures',reportSpread:'Spread Risk',reportAffects:'Affected Crops',
    reportFarmerNote:'Farmer-Reported Symptoms',reportExpert:'Nearest Expert',
    reportFooter:'Generated by KisanMitra AI — Smart Farm Advisory for Every Farmer',
    reportDisclaimer:'This report is AI-generated. Consult your local KVK or agricultural officer before applying any treatment.',
  },
  hi:{
    title:'कीट और रोग पहचान',subtitle:'फसल की फोटो अपलोड करें — AI कीट/रोग पहचानकर उपाय बताएगा',
    uploadTitle:'फसल की फोटो अपलोड करें',dragText:'यहाँ फोटो खींचकर छोड़ें',tapText:'या गैलरी से चुनें',
    sizeText:'JPG / PNG / WEBP, 5MB तक',orText:'या',cameraBtn:'कैमरा खोलें',removeBtn:'फोटो हटाएं',
    symptomsLabel:'लक्षण बताएं (वैकल्पिक)',
    symptomsPlaceholder:'जैसे: पत्तियों पर पीले धब्बे, सफेद चूर्ण...',
    analyzeBtn:'कीट / रोग पहचानें',analyzing:'AI जांच कर रहा है...',
    detected:'पहचान हुई',severity:'गंभीरता',affects:'प्रभावित फसलें',
    symptoms:'लक्षण',chemical:'रासायनिक उपचार',organic:'जैविक उपचार',
    prevention:'बचाव',spreadRisk:'फैलाव का खतरा',nearestExpert:'नजदीकी विशेषज्ञ',
    callExpert:'विशेषज्ञ को कॉल करें',downloadReport:'रिपोर्ट डाउनलोड करें',downloading:'PDF तैयार हो रही है...',
    commonPests:'इस मौसम के सामान्य कीट',low:'कम',moderate:'मध्यम',high:'अधिक',confidence:'विश्वास',
    tipText:'फसल की फोटो अपलोड करें या लक्षण बताएं, फिर "कीट पहचानें" दबाएं।',
    reportTitle:'कीट एवं रोग पहचान रिपोर्ट',reportDate:'दिनांक',reportCrop:'फसल',
    reportSeverity:'गंभीरता स्तर',reportConfidence:'AI विश्वास',reportSymptoms:'देखे गए लक्षण',
    reportChemical:'रासायनिक उपचार',reportOrganic:'जैविक उपचार',reportPrevention:'बचाव के उपाय',
    reportSpread:'फैलाव का खतरा',reportAffects:'प्रभावित फसलें',reportFarmerNote:'किसान द्वारा बताए लक्षण',
    reportExpert:'नजदीकी विशेषज्ञ',
    reportFooter:'KisanMitra AI द्वारा तैयार — हर किसान के लिए स्मार्ट खेती सलाह',
    reportDisclaimer:'यह रिपोर्ट AI द्वारा तैयार की गई है। कोई भी उपचार लागू करने से पहले स्थानीय KVK से परामर्श लें।',
  },
  pa:{
    title:'ਕੀੜੇ ਅਤੇ ਬਿਮਾਰੀ ਦੀ ਪਛਾਣ',subtitle:'ਫਸਲ ਦੀ ਫੋਟੋ ਅਪਲੋਡ ਕਰੋ — AI ਕੀੜੇ/ਬਿਮਾਰੀ ਦੱਸੇਗਾ',
    uploadTitle:'ਫਸਲ ਦੀ ਫੋਟੋ ਅਪਲੋਡ ਕਰੋ',dragText:'ਇੱਥੇ ਫੋਟੋ ਖਿੱਚ ਕੇ ਛੱਡੋ',tapText:'ਜਾਂ ਗੈਲਰੀ ਤੋਂ ਚੁਣੋ',
    sizeText:'JPG / PNG / WEBP, 5MB ਤੱਕ',orText:'ਜਾਂ',cameraBtn:'ਕੈਮਰਾ ਖੋਲੋ',removeBtn:'ਫੋਟੋ ਹਟਾਓ',
    symptomsLabel:'ਲੱਛਣ ਦੱਸੋ (ਵਿਕਲਪਿਕ)',
    symptomsPlaceholder:'ਜਿਵੇਂ: ਪੱਤਿਆਂ ਤੇ ਪੀਲੇ ਧੱਬੇ, ਚਿੱਟਾ ਪਾਊਡਰ...',
    analyzeBtn:'ਕੀੜੇ / ਬਿਮਾਰੀ ਪਛਾਣੋ',analyzing:'AI ਜਾਂਚ ਕਰ ਰਿਹਾ ਹੈ...',
    detected:'ਪਛਾਣ ਹੋਈ',severity:'ਗੰਭੀਰਤਾ',affects:'ਪ੍ਰਭਾਵਿਤ ਫਸਲਾਂ',
    symptoms:'ਲੱਛਣ',chemical:'ਰਸਾਇਣਕ ਇਲਾਜ',organic:'ਜੈਵਿਕ ਇਲਾਜ',
    prevention:'ਬਚਾਅ',spreadRisk:'ਫੈਲਣ ਦਾ ਖਤਰਾ',nearestExpert:'ਨਜ਼ਦੀਕੀ ਮਾਹਿਰ',
    callExpert:'ਮਾਹਿਰ ਨੂੰ ਕਾਲ ਕਰੋ',downloadReport:'ਰਿਪੋਰਟ ਡਾਊਨਲੋਡ ਕਰੋ',downloading:'PDF ਤਿਆਰ ਹੋ ਰਹੀ ਹੈ...',
    commonPests:'ਇਸ ਮੌਸਮ ਦੇ ਆਮ ਕੀੜੇ',low:'ਘੱਟ',moderate:'ਦਰਮਿਆਨਾ',high:'ਵੱਧ',confidence:'ਭਰੋਸਾ',
    tipText:'ਫਸਲ ਦੀ ਫੋਟੋ ਅਪਲੋਡ ਕਰੋ ਜਾਂ ਲੱਛਣ ਦੱਸੋ, ਫਿਰ ਕੀੜੇ ਪਛਾਣੋ ਦਬਾਓ।',
    reportTitle:'ਕੀੜੇ ਅਤੇ ਬਿਮਾਰੀ ਪਛਾਣ ਰਿਪੋਰਟ',reportDate:'ਮਿਤੀ',reportCrop:'ਫਸਲ',
    reportSeverity:'ਗੰਭੀਰਤਾ ਪੱਧਰ',reportConfidence:'AI ਭਰੋਸਾ',reportSymptoms:'ਦੇਖੇ ਗਏ ਲੱਛਣ',
    reportChemical:'ਰਸਾਇਣਕ ਇਲਾਜ',reportOrganic:'ਜੈਵਿਕ ਇਲਾਜ',reportPrevention:'ਬਚਾਅ ਦੇ ਉਪਾਅ',
    reportSpread:'ਫੈਲਣ ਦਾ ਖਤਰਾ',reportAffects:'ਪ੍ਰਭਾਵਿਤ ਫਸਲਾਂ',reportFarmerNote:'ਕਿਸਾਨ ਦੁਆਰਾ ਦੱਸੇ ਲੱਛਣ',
    reportExpert:'ਨਜ਼ਦੀਕੀ ਮਾਹਿਰ',
    reportFooter:'KisanMitra AI ਦੁਆਰਾ — ਹਰ ਕਿਸਾਨ ਲਈ ਸਮਾਰਟ ਖੇਤੀ ਸਲਾਹ',
    reportDisclaimer:'ਇਹ ਰਿਪੋਰਟ AI ਦੁਆਰਾ ਬਣਾਈ ਗਈ ਹੈ। ਕੋਈ ਵੀ ਇਲਾਜ ਤੋਂ ਪਹਿਲਾਂ ਸਥਾਨਕ KVK ਨਾਲ ਸੰਪਰਕ ਕਰੋ।',
  },
  ta:{
    title:'பூச்சி மற்றும் நோய் கண்டறிதல்',subtitle:'பயிர் புகைப்படம் பதிவேற்றவும் — AI பூச்சி/நோயை கண்டறிந்து சிகிச்சை பரிந்துரைக்கும்',
    uploadTitle:'பயிர் புகைப்படம் பதிவேற்றவும்',dragText:'இங்கே புகைப்படத்தை இழுத்து விடவும்',
    tapText:'அல்லது கேலரியிலிருந்து தேர்ந்தெடுக்கவும்',sizeText:'JPG / PNG / WEBP, 5MB வரை',
    orText:'அல்லது',cameraBtn:'கேமராவைத் திறக்கவும்',removeBtn:'புகைப்படம் நீக்கவும்',
    symptomsLabel:'அறிகுறிகளை விவரிக்கவும்',
    symptomsPlaceholder:'எ.கா: இலைகளில் மஞ்சள் திட்டுகள், வெள்ளை பொடி...',
    analyzeBtn:'பூச்சி / நோய் கண்டறியவும்',analyzing:'AI பகுப்பாய்வு செய்கிறது...',
    detected:'கண்டறியப்பட்டது',severity:'தீவிரம்',affects:'பாதிக்கப்பட்ட பயிர்கள்',
    symptoms:'அறிகுறிகள்',chemical:'இரசாயன சிகிச்சை',organic:'இயற்கை சிகிச்சை',
    prevention:'தடுப்பு',spreadRisk:'பரவல் அபாயம்',nearestExpert:'அருகிலுள்ள நிபுணர்',
    callExpert:'நிபுணரை அழைக்கவும்',downloadReport:'அறிக்கை பதிவிறக்கவும்',downloading:'PDF தயாராகிறது...',
    commonPests:'இந்த சீசனில் பொதுவான பூச்சிகள்',low:'குறைவு',moderate:'மிதமானது',high:'அதிகம்',confidence:'நம்பகத்தன்மை',
    tipText:'பயிர் புகைப்படம் பதிவேற்றவும் அல்லது அறிகுறிகளை விவரிக்கவும்.',
    reportTitle:'பூச்சி மற்றும் நோய் கண்டறிதல் அறிக்கை',reportDate:'தேதி',reportCrop:'பயிர்',
    reportSeverity:'தீவிர நிலை',reportConfidence:'AI நம்பகத்தன்மை',reportSymptoms:'அறிகுறிகள்',
    reportChemical:'இரசாயன சிகிச்சை',reportOrganic:'இயற்கை சிகிச்சை',reportPrevention:'தடுப்பு நடவடிக்கைகள்',
    reportSpread:'பரவல் அபாயம்',reportAffects:'பாதிக்கப்பட்ட பயிர்கள்',reportFarmerNote:'விவசாயி தெரிவித்த அறிகுறிகள்',
    reportExpert:'அருகிலுள்ள நிபுணர்',
    reportFooter:'KisanMitra AI மூலம் உருவாக்கப்பட்டது',
    reportDisclaimer:'இந்த அறிக்கை AI மூலம் உருவாக்கப்பட்டது. சிகிச்சைக்கு முன் உள்ளூர் KVK-ஐ தொடர்பு கொள்ளுங்கள்.',
  },
  te:{
    title:'చీడపీడ మరియు వ్యాధి గుర్తింపు',subtitle:'పంట ఫోటో అప్‌లోడ్ చేయండి — AI చీడపీడ గుర్తించి చికిత్స సూచిస్తుంది',
    uploadTitle:'పంట ఫోటో అప్‌లోడ్ చేయండి',dragText:'ఇక్కడ ఫోటో లాగి వదలండి',
    tapText:'లేదా గ్యాలరీ నుండి ఎంచుకోండి',sizeText:'JPG / PNG / WEBP, 5MB వరకు',
    orText:'లేదా',cameraBtn:'కెమెరా తెరవండి',removeBtn:'ఫోటో తీసివేయండి',
    symptomsLabel:'లక్షణాలు వివరించండి',
    symptomsPlaceholder:'ఉదా: ఆకులపై పసుపు మచ్చలు, తెలుపు పొడి...',
    analyzeBtn:'చీడపీడ గుర్తించండి',analyzing:'AI విశ్లేషిస్తోంది...',
    detected:'గుర్తించబడింది',severity:'తీవ్రత',affects:'ప్రభావిత పంటలు',
    symptoms:'లక్షణాలు',chemical:'రసాయన చికిత్స',organic:'సేంద్రీయ చికిత్స',
    prevention:'నివారణ',spreadRisk:'వ్యాప్తి ప్రమాదం',nearestExpert:'సమీప నిపుణుడు',
    callExpert:'నిపుణుడిని కాల్ చేయండి',downloadReport:'నివేదిక డౌన్‌లోడ్',downloading:'PDF సిద్ధమవుతోంది...',
    commonPests:'ఈ సీజన్‌లో సాధారణ చీడలు',low:'తక్కువ',moderate:'మధ్యస్థం',high:'అధికం',confidence:'నమ్మకం',
    tipText:'పంట ఫోటో అప్‌లోడ్ చేయండి లేదా లక్షణాలు వివరించండి.',
    reportTitle:'చీడపీడ మరియు వ్యాధి గుర్తింపు నివేదిక',reportDate:'తేదీ',reportCrop:'పంట',
    reportSeverity:'తీవ్రత స్థాయి',reportConfidence:'AI నమ్మకం',reportSymptoms:'గుర్తించిన లక్షణాలు',
    reportChemical:'రసాయన చికిత్స',reportOrganic:'సేంద్రీయ చికిత్స',reportPrevention:'నివారణ చర్యలు',
    reportSpread:'వ్యాప్తి ప్రమాదం',reportAffects:'ప్రభావిత పంటలు',reportFarmerNote:'రైతు నివేదించిన లక్షణాలు',
    reportExpert:'సమీప నిపుణుడు',
    reportFooter:'KisanMitra AI ద్వారా రూపొందించబడింది',
    reportDisclaimer:'ఈ నివేదిక AI ద్వారా రూపొందించబడింది. చికిత్స వర్తించే ముందు స్థానిక KVK సంప్రదించండి.',
  },
};

const SEV = {
  low: { bg:'bg-green-900/40', border:'border-green-500/40', text:'text-green-400', dot:'bg-green-400', hex:'#22c55e' },
  moderate:{ bg:'bg-amber-900/40', border:'border-amber-500/40', text:'text-amber-400', dot:'bg-amber-400', hex:'#f59e0b' },
  high: { bg:'bg-red-900/40', border:'border-red-500/40', text:'text-red-400', dot:'bg-red-400', hex:'#ef4444' },
};
const COMMON_PESTS = [
  { name:'Powdery Mildew', crop:'Wheat / Mustard', sev:'moderate', icon:'🍃' },
  { name:'Brown Planthopper', crop:'Rice', sev:'high', icon:'🦗' },
  { name:'Aphids', crop:'Mustard / Veggies', sev:'low', icon:'🐛' },
  { name:'Yellow Rust', crop:'Wheat', sev:'high', icon:'🌾' },
  { name:'Fall Armyworm', crop:'Maize / Wheat', sev:'high', icon:'🐛' },
];

// Now takes the detected crop from AI instead of a user-selected value
function resolveAffectedCrops(detection) {
  const backend = Array.isArray(detection?.affectedCrops) ? detection.affectedCrops.filter(Boolean) : [];
  return [...new Set(backend)];
}

function buildReportHTML({ detection, result, form, t, lang, cropLabel, confidence, affectedCrops }) {
  const sevHex = SEV[detection.severity]?.hex || '#f59e0b';
  const sevText = { low:t.low, moderate:t.moderate, high:t.high }[detection.severity] || detection.severity;
  const conf = confidence ?? detection.confidence;
  const dateStr = new Date().toLocaleDateString(
    { hi:'hi-IN', pa:'pa-IN', ta:'ta-IN', te:'te-IN' }[lang] || 'en-IN',
    { day:'numeric', month:'long', year:'numeric' }
  );
  const expert = result?.nearestExpert;

  const row = (label, value) => value
    ? `<tr>
        <td style="padding:7px 11px;font-weight:600;color:#444;width:34%;border-bottom:1px solid #f0fdf4;font-size:11.5px;vertical-align:top;">${label}</td>
        <td style="padding:7px 11px;color:#1a1a1a;border-bottom:1px solid #f0fdf4;line-height:1.45;font-size:11.5px;">${value}</td>
      </tr>`
    : '';

  return `
<div style="font-family:'Segoe UI',Arial,sans-serif;font-size:12.5px;line-height:1.55;color:#1a1a1a;background:#fff;padding:36px 42px;min-height:1060px;">
  <div style="display:flex;justify-content:space-between;align-items:center;padding-bottom:11px;border-bottom:3px solid #15803d;margin-bottom:14px;">
    <div style="display:flex;align-items:center;gap:10px;">
      <div style="width:44px;height:44px;background:linear-gradient(135deg,#15803d,#22c55e);border-radius:10px;display:flex;align-items:center;justify-content:center;font-size:22px;">🌾</div>
      <div>
        <div style="font-size:30px;font-weight:800;color:#15803d;letter-spacing:-0.3px;line-height:1.1;">KisanMitra</div>
        <div style="font-size:11px;color:#666;margin-top:2px;">Smart Farm Advisory · AI Powered</div>
      </div>
    </div>
    <div style="text-align:right;font-size:14px;color:#555;line-height:1.9;">
      <div>${t.reportDate}: <b>${dateStr}</b></div>
      <div>${t.reportCrop}: <b>${cropLabel}</b></div>
    </div>
  </div>
  <div style="font-size:18px;font-weight:700;color:#15803d;margin-bottom:11px;">📋 ${t.reportTitle}</div>
  <div style="background:#f0fdf4;border:1.5px solid #86efac;border-left:4px solid #15803d;border-radius:9px;padding:11px 15px;margin-bottom:13px;display:flex;justify-content:space-between;align-items:flex-start;gap:10px;">
    <div>
      <div style="font-size:16px;font-weight:800;color:#15803d;">🔍 ${detection.name || '—'}</div>
      ${detection.scientific ? `<div style="font-size:10px;color:#888;font-style:italic;margin-top:2px;">${detection.scientific}</div>` : ''}
    </div>
    <div style="padding:4px 12px 12px 12px;border-radius:20px;font-size:11px;font-weight:700;color:#fff;white-space:nowrap;flex-shrink:0;background:${sevHex};">${sevText}</div>
  </div>
  <table style="width:100%;border-collapse:collapse;margin-bottom:12px;border:1px solid #d1fae5;border-radius:8px;overflow:hidden;">
    <thead><tr style="background:#15803d;"><th colspan="2" style="color:#fff;padding:7px 11px 20px 11px;text-align:left;font-size:15px;">📊 ${t.reportTitle}</th></tr></thead>
    <tbody >
      ${row(t.reportSymptoms, detection.symptoms)}
      ${row(t.reportChemical, detection.chemical)}
      ${row(t.reportOrganic, detection.organic)}
      ${row(t.reportPrevention, detection.preventive)}
      ${row(t.reportSpread, detection.spreadRisk)}
    </tbody>
  </table>
  <table style="width:100%;border-collapse:collapse;margin-bottom:12px;border:1px solid #d1fae5;border-radius:8px;overflow:hidden;">
    <thead><tr style="background:#15803d;"><th style="color:#fff;padding:7px 11px 20px 11px;text-align:left;font-size:15px;">${t.reportAffects}</th></tr></thead>
    <tbody><tr><td style="padding:0;">
      <div style="display:flex;flex-wrap:wrap;gap:5px;padding:8px 11px;">
        ${affectedCrops.map((c,i) =>
          `<span style="background:${i===0?'#15803d':'#dcfce7'};color:${i===0?'#fff':'#15803d'};border:1px solid ${i===0?'#15803d':'#86efac'};border-radius:20px;padding:4px 12px 12px 12px;font-size:11px;font-weight:600;">${i===0?'★ ':''}${c}</span>`
        ).join('')}
      </div>
    </td></tr></tbody>
  </table>
  ${form.symptoms ? `
  <table style="width:100%;border-collapse:collapse;margin-bottom:12px;border:1px solid #d1fae5;border-radius:8px;overflow:hidden;">
    <thead><tr style="background:#15803d;"><th style="color:#fff;padding:7px 11px;text-align:left;font-size:11.5px;">📝 ${t.reportFarmerNote}</th></tr></thead>
    <tbody><tr><td style="padding:9px 11px;color:#444;font-size:11.5px;">${form.symptoms}</td></tr></tbody>
  </table>` : ''}
  ${expert ? `
  <div style="font-size:15px;font-weight:700;color:#15803d;margin-bottom:8px;">📍 ${t.reportExpert}</div>
  <div style="background:#f0fdf4;border:1px solid #86efac;border-radius:8px;padding:9px 13px;margin-bottom:12px;display:flex;align-items:center;gap:12px;">
    <span style="font-size:18px;">🏥</span>
    <div>
      <div style="font-weight:700;color:#15803d;font-size:13px;">${expert.name}${expert.type ? ` — ${expert.type}` : ''}</div>
      <div style="font-size:12px;color:#444;margin-top:2px;">📞 ${expert.phone}${expert.distance ? ` &nbsp;&nbsp; 📍 ${expert.distance}` : ''}</div>
    </div>
  </div>` : ''}
  <div style="margin-top:12px;padding-top:9px;border-top:1.5px solid #e5e7eb;display:flex;justify-content:space-between;align-items:flex-end;gap:10px;">
    <div style="font-size:11px;color:#15803d;font-weight:700;">🌾 ${t.reportFooter}</div>
    <div style="font-size:10px;color:#999;max-width:360px;text-align:right;line-height:1.4;">${t.reportDisclaimer}</div>
  </div>
</div>`;
}

export default function PestDetection() {
  const { lang } = useApp();
  const t = TX[lang] || TX.en;

  const [preview, setPreview] = useState(null);
  const [file, setFile] = useState(null);
  const [cameraOpen, setCameraOpen] = useState(false);
  const [form, setForm] = useState({ symptoms:'' }); // Removed 'crop'
  const [result, setResult] = useState(null);
  const [loading, setLoading] = useState(false);
  const [pdfLoading, setPdfLoading] = useState(false);
  const videoRef = useRef(null);
  const streamRef = useRef(null);

  const onDrop = useCallback(files => {
    const f = files[0]; if (!f) return;
    setFile(f); setPreview(URL.createObjectURL(f)); setResult(null); setCameraOpen(false);
  }, []);
  const { getRootProps, getInputProps, isDragActive } = useDropzone({ onDrop, accept:{ 'image/*':[] }, maxFiles:1 });

  const openCamera = async () => {
    try {
      const s = await navigator.mediaDevices.getUserMedia({ video:{ facingMode:'environment' } });
      streamRef.current = s; setCameraOpen(true);
      setTimeout(() => { if (videoRef.current) videoRef.current.srcObject = s; }, 100);
    } catch { toast.error('Camera not available'); }
  };
  const capturePhoto = () => {
    const v = videoRef.current; if (!v) return;
    const c = document.createElement('canvas');
    c.width = v.videoWidth; c.height = v.videoHeight;
    c.getContext('2d').drawImage(v, 0, 0);
    c.toBlob(blob => {
      const f = new File([blob], 'capture.jpg', { type:'image/jpeg' });
      setFile(f); setPreview(URL.createObjectURL(blob)); setResult(null); stopCamera();
    }, 'image/jpeg', 0.92);
  };
  const stopCamera = () => {
    if (streamRef.current) streamRef.current.getTracks().forEach(tr => tr.stop());
    streamRef.current = null; setCameraOpen(false);
  };

  const removeImage = () => { setPreview(null); setFile(null); setResult(null); stopCamera(); };

  const analyze = async () => {
    setLoading(true);
    try {
      const fd = new FormData();
      if (file) fd.append('image', file);
      fd.append('symptoms', form.symptoms);
      fd.append('lang', lang);

      const r = await api.post('/pest/detect', fd, {
        headers: { 'Content-Type': 'multipart/form-data' }
      });

      if (r?.error) {
        const code = r.code;
        if (code === 'NOT_A_CROP_IMAGE') toast.error(r.message, { duration: 5000, icon: '🚫' });
        else if (code === 'LOW_CONFIDENCE') toast.error(r.message, { duration: 5000, icon: '🔍' });
        else if (code === 'PEST_CROP_MISMATCH') toast.error(r.message, { duration: 5000, icon: '⚠️' });
        else toast.error(r.message || 'Detection failed');
        return;
      }

      if (r?.detection) {
        r.detection.affectedCrops = resolveAffectedCrops(r.detection);
      }
      setResult(r);
      toast.success(`${t.detected}: ${r.detection?.name}`);
    } catch (e) {
      const errData = e?.response?.data;
      toast.error(errData?.message || e.message || 'Detection failed', { duration: 5000 });
    } finally {
      setLoading(false);
    }
  };

  const getCropLabel = (cropName) => {
    if (!cropName) return 'Unknown';
    const c = CROPS.find(x => x.label.toLowerCase() === cropName.toLowerCase()); 
    if (!c) return cropName;
    const n = c[lang]; 
    return (n && n !== c.label) ? `${c.label} (${n})` : c.label;
  };

  const ss = sev => SEV[sev] || SEV.moderate;
  const sl = sev => ({ low:t.low, moderate:t.moderate, high:t.high }[sev] || sev);
  const conf = result ? (result.confidence ?? result.detection?.confidence) : null;

  const handleDownload = async () => {
    if (!result?.detection) return;
    setPdfLoading(true);
    const toastId = toast.loading(t.downloading);
    try {
      const affectedCrops = resolveAffectedCrops(result.detection);
      const detectedCrop = affectedCrops[0] || 'Unknown';
      const htmlString = buildReportHTML({
        detection: result.detection, result, form, t, lang,
        cropLabel: getCropLabel(detectedCrop), confidence: conf, affectedCrops,
      });
      const pestName = result.detection.name?.replace(/\s+/g, '_') || 'pest';
      const filename = `KisanMitra_PestReport_${pestName}_${new Date().toISOString().slice(0,10)}.pdf`;
      await downloadPDF({ htmlString, filename });
      toast.success(
        lang==='hi' ? 'रिपोर्ट डाउनलोड हो गई!' :
        lang==='pa' ? 'ਰਿਪੋਰਟ ਡਾਊਨਲੋਡ ਹੋ ਗਈ!' :
        lang==='ta' ? 'அறிக்கை பதிவிறக்கப்பட்டது!' :
        lang==='te' ? 'నివేదిక డౌన్‌లోడ్ అయింది!' :
        'Report downloaded!',
        { id: toastId }
      );
    } catch (err) {
      toast.error('PDF generation failed.', { id: toastId });
    } finally {
      setPdfLoading(false);
    }
  };

  return (
    <div className="space-y-6 p-1">
      <div>
        <h1 className="flex items-center gap-2">
          <span>🔍</span>
          <span className="font-display text-3xl font-bold text-gradient-green">{t.title}</span>
        </h1>
        <p className="text-white/40 text-sm mt-1">{t.subtitle}</p>
      </div>

      <div className="grid md:grid-cols-2 gap-5">
        <div className="bg-white/[0.04] border border-white/10 rounded-2xl p-5 space-y-4">
          <h2 className="font-semibold text-white/80 flex items-center gap-2">📷 {t.uploadTitle}</h2>

          <AnimatePresence>
            {cameraOpen && (
              <motion.div initial={{ opacity:0 }} animate={{ opacity:1 }} exit={{ opacity:0 }}
                className="relative rounded-xl overflow-hidden bg-black">
                <video ref={videoRef} autoPlay playsInline className="w-full rounded-xl max-h-56 object-cover" />
                <div className="absolute inset-x-0 bottom-3 flex justify-center gap-3">
                  <button onClick={capturePhoto} className="bg-green-500 hover:bg-green-400 text-white font-bold px-5 py-2 rounded-full text-sm shadow-lg transition-colors">📸 Capture</button>
                  <button onClick={stopCamera} className="bg-red-600/80 hover:bg-red-500 text-white px-4 py-2 rounded-full text-sm transition-colors">✕ Cancel</button>
                </div>
              </motion.div>
            )}
          </AnimatePresence>

          {!cameraOpen && (
            <div {...getRootProps()} className={`border-2 border-dashed rounded-xl p-6 text-center cursor-pointer transition-all ${isDragActive?'border-green-500/70 bg-green-900/20':'border-white/10 hover:border-green-500/40 hover:bg-white/[0.02]'}`}>
              <input {...getInputProps()} />
              {preview
                ? <img src={preview} alt="Crop" className="max-h-44 mx-auto rounded-lg object-cover shadow-md" />
                : <div><div className="text-5xl mb-3">📸</div><p className="text-white/60 text-sm font-medium">{t.dragText}</p><p className="text-white/30 text-xs mt-1">{t.tapText}</p><p className="text-white/20 text-xs mt-1.5">{t.sizeText}</p></div>
              }
            </div>
          )}
          {!cameraOpen && (
            <>
              <div className="flex items-center gap-3"><div className="flex-1 h-px bg-white/10"/><span className="text-white/30 text-xs">{t.orText}</span><div className="flex-1 h-px bg-white/10"/></div>
              <button onClick={openCamera} className="w-full flex items-center justify-center gap-2 bg-white/[0.06] hover:bg-green-600/20 border border-white/10 hover:border-green-500/40 rounded-xl py-2.5 text-sm text-white/70 hover:text-green-300 transition-all">
                <Camera className="w-4 h-4" /> {t.cameraBtn}
              </button>
            </>
          )}
          {preview && !cameraOpen && (
            <button onClick={removeImage} className="w-full flex items-center justify-center gap-1.5 text-xs text-red-400/70 hover:text-red-400 py-1.5 transition-colors">
              <X className="w-3.5 h-3.5" /> {t.removeBtn}
            </button>
          )}
          <div>
            <label className="text-xs text-white/40 mb-1.5 block font-medium uppercase tracking-wider">{t.symptomsLabel}</label>
            <textarea className="w-full bg-white/[0.06] border border-white/10 rounded-xl px-3 py-2.5 text-sm text-white/80 placeholder:text-white/20 resize-none focus:outline-none focus:border-green-500/50 focus:bg-white/[0.08] transition-colors"
              rows={3} placeholder={t.symptomsPlaceholder}
              value={form.symptoms} onChange={e => setForm(p => ({ ...p, symptoms:e.target.value }))} />
          </div>
          <button onClick={analyze} disabled={loading || (!file && !form.symptoms)}
            className="w-full flex items-center justify-center gap-2 bg-green-600 hover:bg-green-500 disabled:opacity-40 disabled:cursor-not-allowed text-white font-bold py-3 rounded-xl text-sm transition-all shadow-lg shadow-green-900/40">
            {loading ? <><Loader2 className="w-4 h-4 animate-spin" /> {t.analyzing}</> : <><Leaf className="w-4 h-4" /> {t.analyzeBtn}</>}
          </button>
        </div>

        <div>
          <AnimatePresence mode="wait">
            {result?.detection ? (
              <motion.div key="result" initial={{ opacity:0, y:16 }} animate={{ opacity:1, y:0 }} exit={{ opacity:0 }}
                className="bg-white/[0.04] border border-white/10 rounded-2xl p-5 space-y-4">
                <div className="flex items-start justify-between gap-3">
                  <div className="flex-1">
                    <div className="text-xs text-green-400 font-semibold uppercase tracking-wider mb-1 flex items-center gap-1">
                      <CheckCircle2 className="w-3.5 h-3.5" /> {t.detected}
                    </div>
                    <h3 className="text-xl font-bold text-white leading-tight">{result.detection.name}</h3>
                    {result.detection.scientific && <p className="text-white/30 text-xs italic mt-0.5">{result.detection.scientific}</p>}
                  </div>
                  <div className={`flex items-center gap-1.5 border px-3 py-1.5 rounded-full text-xs font-bold ${ss(result.detection.severity).bg} ${ss(result.detection.severity).border} ${ss(result.detection.severity).text}`}>
                    <span className={`w-1.5 h-1.5 rounded-full ${ss(result.detection.severity).dot}`} />
                    {sl(result.detection.severity)}
                  </div>
                </div>
                {conf && (
                  <div>
                    <div className="flex justify-between text-xs text-white/40 mb-1"><span>{t.confidence}</span><span className="text-green-400 font-bold">{Math.round(conf*100)}%</span></div>
                    <div className="h-1.5 bg-white/10 rounded-full overflow-hidden">
                      <motion.div initial={{ width:0 }} animate={{ width:`${Math.round(conf*100)}%` }} transition={{ duration:0.8, ease:'easeOut' }} className="h-full bg-gradient-to-r from-green-500 to-lime-400 rounded-full" />
                    </div>
                  </div>
                )}
                {result.detection.affectedCrops?.length > 0 && (
                  <div>
                    <p className="text-xs text-white/40 mb-2">{t.affects}:</p>
                    <div className="flex flex-wrap gap-1.5">
                      {result.detection.affectedCrops.map((crop, i) => (
                        <span key={crop} className={`text-xs font-semibold px-2.5 py-1 rounded-full border ${i===0?'bg-green-600/40 border-green-500/50 text-green-300':'bg-white/[0.06] border-white/10 text-white/55'}`}>
                          {i===0?'★ ':''}{crop}
                        </span>
                      ))}
                    </div>
                  </div>
                )}
                <div className="space-y-2.5">
                  {[
                    ['🔍', t.symptoms, result.detection.symptoms, 'border-l-white/20'],
                    ['💊', t.chemical, result.detection.chemical, 'border-l-blue-500/40'],
                    ['🌿', t.organic, result.detection.organic, 'border-l-green-500/40'],
                    ['🛡️', t.prevention, result.detection.preventive, 'border-l-purple-500/40'],
                    ['⚡', t.spreadRisk, result.detection.spreadRisk, 'border-l-red-500/40'],
                  ].map(([icon,title,text,border]) => text && (
                    <div key={title} className={`bg-white/[0.04] border border-white/[0.07] border-l-2 ${border} rounded-lg p-3`}>
                      <div className="flex items-center gap-1.5 mb-1"><span className="text-sm">{icon}</span><span className="text-xs font-bold text-white/60 uppercase tracking-wider">{title}</span></div>
                      <p className="text-white/70 text-sm leading-relaxed">{text}</p>
                    </div>
                  ))}
                </div>
                {result.nearestExpert && (
                  <div className="bg-green-900/30 border border-green-500/20 rounded-xl p-3">
                    <div className="text-green-400 font-semibold text-xs mb-1.5">📍 {t.nearestExpert}</div>
                    <p className="text-white/70 text-sm font-medium">{result.nearestExpert.name}{result.nearestExpert.distance?` · ${result.nearestExpert.distance}`:''}</p>
                    {result.nearestExpert.phone && <p className="text-white/40 text-xs mt-0.5">📞 {result.nearestExpert.phone}</p>}
                  </div>
                )}
                <div className="flex gap-2 pt-1">
                  <button
                    onClick={() => result.nearestExpert?.phone ? window.open(`tel:${result.nearestExpert.phone}`,'_self') : toast('No expert contact available')}
                    className="flex-1 flex items-center justify-center gap-1.5 bg-green-600/20 border border-green-500/30 text-green-300 text-xs font-semibold py-2.5 rounded-xl transition-all hover:bg-green-600 hover:text-white hover:border-green-500">
                    📞 {t.callExpert}
                  </button>
                  <motion.button
                    whileHover={{ scale:1.02 }} whileTap={{ scale:0.97 }}
                    onClick={handleDownload} disabled={pdfLoading}
                    className="flex-1 flex items-center justify-center gap-1.5 bg-green-600/20 border border-green-500/30 text-green-300 text-xs font-semibold py-2.5 rounded-xl transition-all hover:bg-green-600 hover:text-white hover:border-green-500 disabled:opacity-60 disabled:cursor-not-allowed"
                  >
                    {pdfLoading ? <><Loader2 className="w-3.5 h-3.5 animate-spin" /> {t.downloading}</> : <><Download className="w-3.5 h-3.5" /> {t.downloadReport}</>}
                  </motion.button>
                </div>
              </motion.div>
            ) : (
              <motion.div key="common" initial={{ opacity:0 }} animate={{ opacity:1 }} exit={{ opacity:0 }}
                className="bg-white/[0.04] border border-white/10 rounded-2xl p-5">
                <h3 className="font-semibold text-white/60 text-sm mb-4 flex items-center gap-2"><AlertTriangle className="w-4 h-4 text-amber-400" /> {t.commonPests}</h3>
                <div className="space-y-0.5">
                  {COMMON_PESTS.map(p => {
                    const s = ss(p.sev);
                    return (
                      <div key={p.name} className="flex items-center gap-3 py-2.5 border-b border-white/[0.05] last:border-0">
                        <span className="text-2xl w-8 text-center">{p.icon}</span>
                        <div className="flex-1 min-w-0"><p className="text-sm font-semibold text-white/85 truncate">{p.name}</p><p className="text-xs text-white/30 truncate">{p.crop}</p></div>
                        <span className={`flex-shrink-0 flex items-center gap-1 border px-2.5 py-1 rounded-full text-[0.65rem] font-bold ${s.bg} ${s.border} ${s.text}`}><span className={`w-1 h-1 rounded-full ${s.dot}`} /> {sl(p.sev)}</span>
                      </div>
                    );
                  })}
                </div>
                <div className="mt-4 bg-green-900/20 border border-green-500/15 rounded-xl p-3 flex gap-2">
                  <Info className="w-4 h-4 text-green-400 flex-shrink-0 mt-0.5" />
                  <p className="text-white/40 text-xs leading-relaxed">{t.tipText}</p>
                </div>
              </motion.div>
            )}
          </AnimatePresence>
        </div>
      </div>
    </div>
  );
}
