/**
 * SoilHealth v2 — Direct PDF download (no popup, no save dialog)
 * Replace the downloadSoilReport function and Download button from Document 8.
 * Everything else (state, form, API call, result UI) is unchanged.
 *
 * Requires: reportUtils.js placed at src/utils/reportUtils.js
 */

import { useState } from 'react';
import { motion, AnimatePresence } from 'framer-motion';
import { RadarChart, PolarGrid, PolarAngleAxis, Radar, ResponsiveContainer } from 'recharts';
import api from '../utils/api';
import toast from 'react-hot-toast';
import { useApp } from '../context/AppContext';
import INDIA_STATES_CITIES from '../utils/indiaCities';
import { Download, Loader2 } from 'lucide-react';
import { downloadPDF } from '../utils/reportUtils';   // ← shared PDF util

// ─── (Keep SOIL_MAP, DISTRICT_SOIL, detectSoilType, SOIL_LABELS, TX, PARAM_KEYS,
//      DEFAULTS, STATES, STATUS_STYLE, STATUS_HEX, ALERT_STYLE exactly as in
//      Document 8 — they are unchanged) ────────────────────────────────────────

const SOIL_MAP = {
  Punjab:'alluvial', Haryana:'alluvial', 'Uttar Pradesh':'alluvial',
  Bihar:'alluvial', 'West Bengal':'alluvial', Assam:'alluvial',
  Maharashtra:'black', Gujarat:'black', 'Madhya Pradesh':'black',
  'Andhra Pradesh':'red', Telangana:'red', 'Tamil Nadu':'red', Karnataka:'red',
  Rajasthan:'sandy', Kerala:'clay',
};
const DISTRICT_SOIL = {
  Guntur:'black', Nalgonda:'black', Warangal:'black',
  Visakhapatnam:'red', Kakinada:'red',
  Fazilka:'sandy', Muktsar:'sandy', Bathinda:'sandy',
  Ganganagar:'alluvial', Hanumangarh:'alluvial',
};
function detectSoilType(state, district) {
  return DISTRICT_SOIL[district] || SOIL_MAP[state] || 'alluvial';
}
const SOIL_LABELS = {
  alluvial:{ en:'Alluvial',  hi:'जलोढ़',       pa:'ਜਲੋੜ੍ਹ',     ta:'வண்டல்',       te:'ఒండ్రు'     },
  black:   { en:'Black',     hi:'काली मिट्टी', pa:'ਕਾਲੀ ਮਿੱਟੀ', ta:'கருப்பு மண்',  te:'నల్ల నేల'   },
  red:     { en:'Red',       hi:'लाल मिट्टी',  pa:'ਲਾਲ ਮਿੱਟੀ',  ta:'சிவப்பு மண்', te:'ఎర్ర నేల'   },
  sandy:   { en:'Sandy',     hi:'बलुई मिट्टी', pa:'ਰੇਤਲੀ ਮਿੱਟੀ',ta:'மணல் மண்',    te:'ఇసుక నేల'   },
  clay:    { en:'Clay',      hi:'चिकनी मिट्टी',pa:'ਚਿਕਨੀ ਮਿੱਟੀ', ta:'களிமண்',       te:'బంకమట్టి నేల'},
  laterite:{ en:'Laterite',  hi:'लेटराइट',     pa:'ਲੈਟਰਾਈਟ',    ta:'லேட்டரைட்',   te:'లేటరైట్'    },
};
const SOIL_TYPES  = Object.keys(SOIL_LABELS);
const PARAM_KEYS  = ['ph','organicCarbon','nitrogen','phosphorus','potassium','zinc'];
const DEFAULTS    = { ph:7.2, organicCarbon:0.42, nitrogen:180, phosphorus:12, potassium:210, zinc:0.6 };
const STATES      = Object.keys(INDIA_STATES_CITIES).sort();

// full TX object — identical to Document 8, included here for completeness
const TX = {
  en:{
    title:'Soil Health Analysis',subtitle:'Enter your Soil Health Card values for personalised fertilizer recommendations',
    inputTitle:'Enter Soil Parameters',soilTypeLabel:'Soil Type',soilTypeAuto:'✦ auto-detected',
    stateLabel:'State',districtLabel:'District',analyzeBtn:'Analyze Soil Health',analyzing:'Analyzing...',
    reportTitle:'Soil Health Report',recommendations:'Recommendations',fertSchedule:'Fertilizer Schedule',
    optimal:'Optimal',downloadReport:'Download Report',downloading:'Generating PDF...',
    rptTitle:'Soil Health Analysis Report',rptDate:'Date',rptLocation:'Location',rptSoilType:'Soil Type',
    rptScore:'Soil Health Score',rptGrade:'Grade',rptParameters:'Soil Parameter Analysis',
    rptParam:'Parameter',rptValue:'Value',rptStatus:'Status',rptOptimal:'Optimal Range',
    rptRecommendations:'Recommendations',rptFertSchedule:'Fertilizer Schedule',rptCrop:'Crop',
    rptFooter:'Generated by KisanMitra AI — Smart Farm Advisory for Every Farmer',
    rptDisclaimer:'This report is AI-generated advisory. Consult your local KVK or agriculture officer before applying amendments.',
    params:{
      ph:           {label:'Soil pH',        unit:'',      optimal:'6.5 – 7.5'},
      organicCarbon:{label:'Organic Carbon', unit:'%',     optimal:'0.8 – 2.0'},
      nitrogen:     {label:'Nitrogen (N)',   unit:'kg/ha', optimal:'250 – 450'},
      phosphorus:   {label:'Phosphorus (P)', unit:'kg/ha', optimal:'20 – 50'  },
      potassium:    {label:'Potassium (K)',  unit:'kg/ha', optimal:'180 – 350'},
      zinc:         {label:'Zinc (Zn)',      unit:'ppm',   optimal:'0.8 – 3.0'},
    },
    statusLabel:{optimal:'Optimal',deficient:'Deficient',critically_low:'Critical Low',high:'High',excess:'Excess'},
  },
  hi:{
    title:'मिट्टी स्वास्थ्य जांच',subtitle:'अपने मृदा स्वास्थ्य कार्ड के मान दर्ज करें — व्यक्तिगत खाद सिफारिशें पाएं',
    inputTitle:'मिट्टी के पैरामीटर दर्ज करें',soilTypeLabel:'मिट्टी का प्रकार',soilTypeAuto:'✦ स्वतः पहचान',
    stateLabel:'राज्य',districtLabel:'जिला',analyzeBtn:'मिट्टी की जांच करें',analyzing:'जांच हो रही है...',
    reportTitle:'मिट्टी स्वास्थ्य रिपोर्ट',recommendations:'सिफारिशें',fertSchedule:'खाद अनुसूची',
    optimal:'उपयुक्त',downloadReport:'रिपोर्ट डाउनलोड करें',downloading:'PDF तैयार हो रही है...',
    rptTitle:'मिट्टी स्वास्थ्य जांच रिपोर्ट',rptDate:'दिनांक',rptLocation:'स्थान',rptSoilType:'मिट्टी का प्रकार',
    rptScore:'मिट्टी स्वास्थ्य स्कोर',rptGrade:'ग्रेड',rptParameters:'मिट्टी पैरामीटर विश्लेषण',
    rptParam:'पैरामीटर',rptValue:'मान',rptStatus:'स्थिति',rptOptimal:'उपयुक्त सीमा',
    rptRecommendations:'सिफारिशें',rptFertSchedule:'खाद अनुसूची',rptCrop:'फसल',
    rptFooter:'KisanMitra AI द्वारा तैयार — हर किसान के लिए स्मार्ट खेती सलाह',
    rptDisclaimer:'यह रिपोर्ट AI द्वारा तैयार की गई है। कोई भी सुधार करने से पहले अपने स्थानीय KVK से परामर्श लें।',
    params:{
      ph:           {label:'मिट्टी pH',    unit:'',      optimal:'6.5 – 7.5'},
      organicCarbon:{label:'जैव कार्बन',   unit:'%',     optimal:'0.8 – 2.0'},
      nitrogen:     {label:'नाइट्रोजन (N)',unit:'kg/ha', optimal:'250 – 450'},
      phosphorus:   {label:'फास्फोरस (P)', unit:'kg/ha', optimal:'20 – 50'  },
      potassium:    {label:'पोटाशियम (K)', unit:'kg/ha', optimal:'180 – 350'},
      zinc:         {label:'जिंक (Zn)',    unit:'ppm',   optimal:'0.8 – 3.0'},
    },
    statusLabel:{optimal:'उपयुक्त',deficient:'कमी',critically_low:'गंभीर कमी',high:'अधिक',excess:'अत्यधिक'},
  },
  pa:{
    title:'ਮਿੱਟੀ ਸਿਹਤ ਜਾਂਚ',subtitle:'ਆਪਣੇ ਮਿੱਟੀ ਸਿਹਤ ਕਾਰਡ ਦੇ ਮੁੱਲ ਦਰਜ ਕਰੋ',
    inputTitle:'ਮਿੱਟੀ ਦੇ ਮਾਪਦੰਡ ਦਰਜ ਕਰੋ',soilTypeLabel:'ਮਿੱਟੀ ਦੀ ਕਿਸਮ',soilTypeAuto:'✦ ਸਵੈ-ਪਛਾਣ',
    stateLabel:'ਰਾਜ',districtLabel:'ਜ਼ਿਲ੍ਹਾ',analyzeBtn:'ਮਿੱਟੀ ਦੀ ਜਾਂਚ ਕਰੋ',analyzing:'ਜਾਂਚ ਹੋ ਰਹੀ ਹੈ...',
    reportTitle:'ਮਿੱਟੀ ਸਿਹਤ ਰਿਪੋਰਟ',recommendations:'ਸਿਫ਼ਾਰਿਸ਼ਾਂ',fertSchedule:'ਖਾਦ ਅਨੁਸੂਚੀ',
    optimal:'ਉਚਿਤ',downloadReport:'ਰਿਪੋਰਟ ਡਾਊਨਲੋਡ ਕਰੋ',downloading:'PDF ਤਿਆਰ ਹੋ ਰਹੀ ਹੈ...',
    rptTitle:'ਮਿੱਟੀ ਸਿਹਤ ਜਾਂਚ ਰਿਪੋਰਟ',rptDate:'ਮਿਤੀ',rptLocation:'ਸਥਾਨ',rptSoilType:'ਮਿੱਟੀ ਦੀ ਕਿਸਮ',
    rptScore:'ਮਿੱਟੀ ਸਿਹਤ ਸਕੋਰ',rptGrade:'ਗ੍ਰੇਡ',rptParameters:'ਮਿੱਟੀ ਪੈਰਾਮੀਟਰ ਵਿਸ਼ਲੇਸ਼ਣ',
    rptParam:'ਪੈਰਾਮੀਟਰ',rptValue:'ਮੁੱਲ',rptStatus:'ਸਥਿਤੀ',rptOptimal:'ਉਚਿਤ ਸੀਮਾ',
    rptRecommendations:'ਸਿਫ਼ਾਰਿਸ਼ਾਂ',rptFertSchedule:'ਖਾਦ ਅਨੁਸੂਚੀ',rptCrop:'ਫਸਲ',
    rptFooter:'KisanMitra AI ਦੁਆਰਾ — ਹਰ ਕਿਸਾਨ ਲਈ ਸਮਾਰਟ ਖੇਤੀ ਸਲਾਹ',
    rptDisclaimer:'ਇਹ ਰਿਪੋਰਟ AI ਦੁਆਰਾ ਬਣਾਈ ਗਈ ਹੈ। ਕੋਈ ਵੀ ਸੁਧਾਰ ਕਰਨ ਤੋਂ ਪਹਿਲਾਂ ਸਥਾਨਕ KVK ਨਾਲ ਸੰਪਰਕ ਕਰੋ।',
    params:{
      ph:           {label:'ਮਿੱਟੀ pH',       unit:'',      optimal:'6.5 – 7.5'},
      organicCarbon:{label:'ਜੈਵਿਕ ਕਾਰਬਨ',    unit:'%',     optimal:'0.8 – 2.0'},
      nitrogen:     {label:'ਨਾਈਟ੍ਰੋਜਨ (N)',  unit:'kg/ha', optimal:'250 – 450'},
      phosphorus:   {label:'ਫਾਸਫੋਰਸ (P)',    unit:'kg/ha', optimal:'20 – 50'  },
      potassium:    {label:'ਪੋਟਾਸ਼ੀਅਮ (K)',  unit:'kg/ha', optimal:'180 – 350'},
      zinc:         {label:'ਜ਼ਿੰਕ (Zn)',     unit:'ppm',   optimal:'0.8 – 3.0'},
    },
    statusLabel:{optimal:'ਉਚਿਤ',deficient:'ਕਮੀ',critically_low:'ਗੰਭੀਰ ਕਮੀ',high:'ਵੱਧ',excess:'ਬਹੁਤ ਵੱਧ'},
  },
  ta:{
    title:'மண் ஆரோக்கிய பகுப்பாய்வு',subtitle:'உங்கள் மண் ஆரோக்கிய அட்டை மதிப்புகளை உள்ளிடவும்',
    inputTitle:'மண் அளவுருக்களை உள்ளிடவும்',soilTypeLabel:'மண் வகை',soilTypeAuto:'✦ தானாக கண்டறியப்பட்டது',
    stateLabel:'மாநிலம்',districtLabel:'மாவட்டம்',analyzeBtn:'மண் ஆரோக்கியம் பகுப்பாய்வு செய்யவும்',
    analyzing:'பகுப்பாய்வு நடைபெறுகிறது...',reportTitle:'மண் ஆரோக்கிய அறிக்கை',
    recommendations:'பரிந்துரைகள்',fertSchedule:'உர அட்டவணை',optimal:'உகந்த',
    downloadReport:'அறிக்கை பதிவிறக்கவும்',downloading:'PDF தயாராகிறது...',
    rptTitle:'மண் ஆரோக்கிய பகுப்பாய்வு அறிக்கை',rptDate:'தேதி',rptLocation:'இடம்',rptSoilType:'மண் வகை',
    rptScore:'மண் ஆரோக்கிய மதிப்பெண்',rptGrade:'தரம்',rptParameters:'மண் அளவுரு பகுப்பாய்வு',
    rptParam:'அளவுரு',rptValue:'மதிப்பு',rptStatus:'நிலை',rptOptimal:'உகந்த வரம்பு',
    rptRecommendations:'பரிந்துரைகள்',rptFertSchedule:'உர அட்டவணை',rptCrop:'பயிர்',
    rptFooter:'KisanMitra AI மூலம் உருவாக்கப்பட்டது',
    rptDisclaimer:'இந்த அறிக்கை AI மூலம் உருவாக்கப்பட்டது. திருத்தங்கள் செய்வதற்கு முன் உள்ளூர் KVK-ஐ தொடர்பு கொள்ளுங்கள்.',
    params:{
      ph:           {label:'மண் pH',          unit:'',      optimal:'6.5 – 7.5'},
      organicCarbon:{label:'கரிம கார்பன்',    unit:'%',     optimal:'0.8 – 2.0'},
      nitrogen:     {label:'நைட்ரஜன் (N)',    unit:'kg/ha', optimal:'250 – 450'},
      phosphorus:   {label:'பாஸ்பரஸ் (P)',    unit:'kg/ha', optimal:'20 – 50'  },
      potassium:    {label:'பொட்டாசியம் (K)', unit:'kg/ha', optimal:'180 – 350'},
      zinc:         {label:'துத்தநாகம் (Zn)', unit:'ppm',   optimal:'0.8 – 3.0'},
    },
    statusLabel:{optimal:'உகந்த',deficient:'குறைபாடு',critically_low:'மிகவும் குறைவு',high:'அதிகம்',excess:'மிகவும் அதிகம்'},
  },
  te:{
    title:'నేల ఆరోగ్య విశ్లేషణ',subtitle:'మీ నేల ఆరోగ్య కార్డ్ విలువలు నమోదు చేయండి',
    inputTitle:'నేల పారామీటర్లు నమోదు చేయండి',soilTypeLabel:'నేల రకం',soilTypeAuto:'✦ స్వయంచాలకంగా గుర్తించబడింది',
    stateLabel:'రాష్ట్రం',districtLabel:'జిల్లా',analyzeBtn:'నేల ఆరోగ్యం విశ్లేషించండి',
    analyzing:'విశ్లేషిస్తోంది...',reportTitle:'నేల ఆరోగ్య నివేదిక',
    recommendations:'సిఫార్సులు',fertSchedule:'ఎరువు షెడ్యూల్',optimal:'అనుకూలం',
    downloadReport:'నివేదిక డౌన్‌లోడ్',downloading:'PDF సిద్ధమవుతోంది...',
    rptTitle:'నేల ఆరోగ్య విశ్లేషణ నివేదిక',rptDate:'తేదీ',rptLocation:'స్థానం',rptSoilType:'నేల రకం',
    rptScore:'నేల ఆరోగ్య స్కోర్',rptGrade:'గ్రేడ్',rptParameters:'నేల పారామీటర్ విశ్లేషణ',
    rptParam:'పారామీటర్',rptValue:'విలువ',rptStatus:'స్థితి',rptOptimal:'అనుకూల శ్రేణి',
    rptRecommendations:'సిఫార్సులు',rptFertSchedule:'ఎరువు షెడ్యూల్',rptCrop:'పంట',
    rptFooter:'KisanMitra AI ద్వారా రూపొందించబడింది',
    rptDisclaimer:'ఈ నివేదిక AI ద్వారా రూపొందించబడింది. సవరణలు చేయడానికి ముందు స్థానిక KVK సంప్రదించండి.',
    params:{
      ph:           {label:'నేల pH',           unit:'',      optimal:'6.5 – 7.5'},
      organicCarbon:{label:'సేంద్రీయ కార్బన్', unit:'%',     optimal:'0.8 – 2.0'},
      nitrogen:     {label:'నత్రజని (N)',       unit:'kg/ha', optimal:'250 – 450'},
      phosphorus:   {label:'భాస్వరం (P)',       unit:'kg/ha', optimal:'20 – 50'  },
      potassium:    {label:'పొటాషియం (K)',      unit:'kg/ha', optimal:'180 – 350'},
      zinc:         {label:'జింక్ (Zn)',        unit:'ppm',   optimal:'0.8 – 3.0'},
    },
    statusLabel:{optimal:'అనుకూలం',deficient:'లోపం',critically_low:'తీవ్రమైన లోపం',high:'అధికం',excess:'మితిమీరిన'},
  },
};

const STATUS_STYLE = {
  optimal:'text-green-400', deficient:'text-amber-400', critically_low:'text-red-400',
  high:'text-blue-400', excess:'text-orange-400',
};
const STATUS_HEX = {
  optimal:'#22c55e', deficient:'#f59e0b', critically_low:'#ef4444',
  high:'#60a5fa', excess:'#f97316',
};
const ALERT_STYLE = {
  success:'glass-green border-green-500/20 text-green-300',
  info:   'border-sky-500/20 bg-sky-900/20 text-sky-300',
  warning:'border-amber-500/20 bg-amber-900/20 text-amber-300',
  danger: 'border-red-500/20 bg-red-900/20 text-red-300',
};

// ─── Build the report HTML string (rendered off-screen for PDF capture) ───────
function buildReportHTML({ result, form, soilType, location, t, lang }) {
  const dateStr = new Date().toLocaleDateString(
    { hi:'hi-IN', pa:'pa-IN', ta:'ta-IN', te:'te-IN' }[lang] || 'en-IN',
    { day:'numeric', month:'long', year:'numeric' }
  );

  const soilLabel  = SOIL_LABELS[soilType]?.[lang] || SOIL_LABELS[soilType]?.en || soilType;
  const scoreColor = result.score >= 75 ? '#22c55e' : result.score >= 50 ? '#f59e0b' : '#ef4444';

  const paramRows = PARAM_KEYS.map(key => {
    const p   = result.parameters?.[key];
    const tp  = t.params[key];
    const stl = t.statusLabel?.[p?.status] || p?.status || '';
    const hex = STATUS_HEX[p?.status] || '#888';
    const pct = Math.round(((p?.score || 0) / (p?.maxScore || 1)) * 100);

    return `<tr>
      <td style="padding:9px 12px;font-weight:600;color:#333;font-size:13px;border-bottom:1px solid #f0fdf4;">
        ${tp?.label || key}
      </td>

      <td style="padding:9px 12px;font-size:13px;border-bottom:1px solid #f0fdf4;">
        ${p?.value ?? '—'} ${tp?.unit || ''}
      </td>

      <td style="padding:9px 12px;font-size:13px;border-bottom:1px solid #f0fdf4;">
        <div style="display:flex;align-items:center;gap:8px;">
          <div style="flex:1;height:7px;background:#e5e7eb;border-radius:10px;overflow:hidden;">
            <div style="width:${pct}%;height:100%;background:${hex};border-radius:10px;"></div>
          </div>
          <span style="color:${hex};font-weight:700;font-size:12px;">${stl}</span>
        </div>
      </td>

      <td style="padding:9px 12px;font-size:12px;color:#666;border-bottom:1px solid #f0fdf4;">
        ${tp?.optimal || ''}
      </td>
    </tr>`;
  }).join('');

  return `
<div style="font-family:'Segoe UI',Arial,sans-serif;font-size:14px;line-height:1.6;color:#1a1a1a;background:#fff;padding:40px 46px;min-height:1060px;">

  <!-- Header -->
  <div style="display:flex;justify-content:space-between;align-items:center;padding-bottom:14px;border-bottom:3px solid #15803d;margin-bottom:16px;">

    <div style="display:flex;align-items:center;gap:12px;">
      <div style="width:48px;height:48px;background:linear-gradient(135deg,#15803d,#22c55e);border-radius:12px;display:flex;align-items:center;justify-content:center;font-size:24px;">🌾</div>

      <div>
        <div style="font-size:30px;font-weight:800;color:#15803d;">KisanMitra</div>
        <div style="font-size:11px;color:#666;">Smart Farm Advisory · AI Powered</div>
      </div>
    </div>

    <div style="text-align:right;font-size:13px;color:#555;line-height:1.8;">
      <div>${t.rptDate}: <b>${dateStr}</b></div>
      ${location ? `<div>${t.rptLocation}: <b>${location}</b></div>` : ''}
      <div>${t.rptSoilType}: <b>${soilLabel}</b></div>
    </div>

  </div>

  <!-- Title -->
  <div style="font-size:18px;font-weight:800;color:#15803d;margin-bottom:14px;">
    🪱 ${t.rptTitle}
  </div>

  <!-- Score Card -->
  <div style="background:#f0fdf4;border:1.5px solid #86efac;border-left:5px solid #15803d;border-radius:10px;padding:14px 18px;margin-bottom:16px;display:flex;align-items:center;gap:22px;">

    <div style="width:80px;height:80px;border-radius:50%;border:4px solid ${scoreColor};display:flex;flex-direction:column;align-items:center;justify-content:center;">
      <div style="font-size:26px;font-weight:800;color:${scoreColor};">${result.score}</div>
      <div style="font-size:11px;color:#888;">/100</div>
    </div>

    <div>
      <div style="font-size:22px;font-weight:800;color:${scoreColor};">${result.grade}</div>
      <div style="font-size:14px;color:#555;margin-top:2px;">${result.rating}</div>

      <div style="font-size:13px;color:#777;margin-top:6px;">
        ${t.rptScore}: <b>${result.score}/100</b>
      </div>
    </div>

  </div>

  <!-- Parameter Table -->
  <div style="font-size:16px;font-weight:700;color:#15803d;margin-bottom:10px;">
    📊 ${t.rptParameters}
  </div>

  <table style="width:100%;border-collapse:collapse;margin-bottom:16px;border:1px solid #d1fae5;border-radius:8px;overflow:hidden;">

    <thead>
      <tr style="background:#15803d;">
        <th style="color:#fff;padding:10px 12px;text-align:left;font-size:13px;">${t.rptParam}</th>
        <th style="color:#fff;padding:10px 12px;text-align:left;font-size:13px;">${t.rptValue}</th>
        <th style="color:#fff;padding:10px 12px;text-align:left;font-size:13px;">${t.rptStatus}</th>
        <th style="color:#fff;padding:10px 12px;text-align:left;font-size:13px;">${t.rptOptimal}</th>
      </tr>
    </thead>

    <tbody>
      ${paramRows}
    </tbody>

  </table>

  <!-- Footer -->
  <div style="margin-top:14px;padding-top:10px;border-top:1.5px solid #e5e7eb;display:flex;justify-content:space-between;align-items:flex-end;gap:10px;">
    <div style="font-size:12px;color:#15803d;font-weight:700;">🌾 ${t.rptFooter}</div>

    <div style="font-size:11px;color:#999;max-width:360px;text-align:right;line-height:1.4;">
      ${t.rptDisclaimer}
    </div>
  </div>

</div>`;
}

// ─── MAIN COMPONENT ───────────────────────────────────────────────────────────
export default function SoilHealth() {
  const { farmer, lang } = useApp();
  const t = TX[lang] || TX.en;

  const defaultState    = farmer?.state    || 'Punjab';
  const defaultDistrict = farmer?.district || (INDIA_STATES_CITIES[defaultState]?.[0] || 'Phagwara');

  const [state,      setState]      = useState(defaultState);
  const [district,   setDistrict]   = useState(defaultDistrict);
  const [soilType,   setSoilType]   = useState(detectSoilType(defaultState, defaultDistrict));
  const [form,       setForm]       = useState(DEFAULTS);
  const [result,     setResult]     = useState(null);
  const [loading,    setLoading]    = useState(false);
  const [pdfLoading, setPdfLoading] = useState(false);

  const handleStateChange = (newState) => {
    const districts   = INDIA_STATES_CITIES[newState] || [];
    const newDistrict = districts[0] || '';
    setState(newState); setDistrict(newDistrict);
    setSoilType(detectSoilType(newState, newDistrict));
  };
  const handleDistrictChange = (d) => {
    setDistrict(d); setSoilType(detectSoilType(state, d));
  };

  const submit = async () => {
    setLoading(true);
    try {
      const r = await api.post('/soil/analyze', { ...form, soilType, lang });
      setResult(r);
      toast.success(`${t.reportTitle}: ${r.score}/100`);
    } catch (e) { toast.error(e.message || 'Analysis failed'); }
    finally { setLoading(false); }
  };

  // ── Direct PDF download — no popup, no dialog ─────────────────────────────
  const handleDownload = async () => {
    if (!result) return;
    setPdfLoading(true);
    const toastId = toast.loading(t.downloading);
    try {
      const locationStr = district && state ? `${district}, ${state}` : null;
      const htmlString  = buildReportHTML({ result, form, soilType, location: locationStr, t, lang });
      const filename    = `KisanMitra_SoilHealth_${state}_${new Date().toISOString().slice(0,10)}.pdf`;
      await downloadPDF({ htmlString, filename });
      toast.success(lang === 'hi' ? 'रिपोर्ट डाउनलोड हो गई!' :
                    lang === 'pa' ? 'ਰਿਪੋਰਟ ਡਾਊਨਲੋਡ ਹੋ ਗਈ!' :
                    lang === 'ta' ? 'அறிக்கை பதிவிறக்கப்பட்டது!' :
                    lang === 'te' ? 'నివేదిక డౌన్‌లోడ్ అయింది!' :
                    'Report downloaded!', { id: toastId });
    } catch (err) {
      toast.error('PDF generation failed. Please try again.', { id: toastId });
    } finally {
      setPdfLoading(false);
    }
  };

  const radarData = PARAM_KEYS.map(key => ({
    subject: t.params[key]?.label?.split(' ')[0] || key,
    score:   result?.parameters?.[key]?.score    || 0,
    max:     result?.parameters?.[key]?.maxScore || 20,
  }));

  const getSoilLabel = (type) =>
    SOIL_LABELS[type]?.[lang] || SOIL_LABELS[type]?.en || type;

  return (
    <div className="space-y-6">
      <div>
        <h1 className="font-display text-3xl font-bold text-gradient-gold">🪱 {t.title}</h1>
        <p className="text-white/40 text-sm mt-1">{t.subtitle}</p>
      </div>

      {/* Input form */}
      <div className="card-gradient rounded-2xl p-6">
        <h2 className="font-semibold text-white/70 mb-4">{t.inputTitle}</h2>
        <div className="grid grid-cols-1 sm:grid-cols-2 gap-4 mb-4">
          <div>
            <label className="text-xs text-white/40 mb-1 block font-medium">{t.stateLabel}</label>
            <select className="input-dark" value={state} onChange={e => handleStateChange(e.target.value)}>
              {STATES.map(s => <option key={s} value={s}>{s}</option>)}
            </select>
          </div>
          <div>
            <label className="text-xs text-white/40 mb-1 block font-medium">{t.districtLabel}</label>
            <select className="input-dark" value={district} onChange={e => handleDistrictChange(e.target.value)}>
              {(INDIA_STATES_CITIES[state] || [district]).map(d => <option key={d} value={d}>{d}</option>)}
            </select>
          </div>
        </div>
        <div className="mb-4">
          <label className="text-xs text-white/40 mb-1 flex items-center gap-1.5 font-medium">
            {t.soilTypeLabel}
            <span className="text-green-500/60 text-[0.6rem] border border-green-500/30 rounded px-1.5 py-0.5 font-normal">{t.soilTypeAuto}</span>
          </label>
          <select className="input-dark" value={soilType} onChange={e => setSoilType(e.target.value)}>
            {SOIL_TYPES.map(st => (
              <option key={st} value={st}>
                {getSoilLabel(st)}{SOIL_LABELS[st]?.en && SOIL_LABELS[st].en !== getSoilLabel(st) ? ` (${SOIL_LABELS[st].en})` : ''}
              </option>
            ))}
          </select>
          <div className="mt-1.5 flex items-center gap-1.5">
            <span className="w-2 h-2 rounded-full bg-green-500/60 inline-block" />
            <span className="text-[0.65rem] text-green-500/50">
              {lang === 'hi' ? `${district}, ${state} के लिए स्वतः पहचाना गया` :
               lang === 'pa' ? `${district}, ${state} ਲਈ ਸਵੈ-ਪਛਾਣਿਆ ਗਿਆ` :
               lang === 'ta' ? `${district}, ${state} க்கு தானாக கண்டறியப்பட்டது` :
               lang === 'te' ? `${district}, ${state} కోసం స్వయంచాలకంగా గుర్తించబడింది` :
               `Auto-detected for ${district}, ${state}`}
            </span>
          </div>
        </div>
        <div className="grid grid-cols-2 sm:grid-cols-3 gap-4">
          {PARAM_KEYS.map(key => {
            const p = t.params[key];
            return (
              <div key={key}>
                <label className="text-xs text-white/40 mb-1 block font-medium">
                  {p.label} {p.unit && <span className="text-white/25">({p.unit})</span>}
                </label>
                <input type="number" className="input-dark" value={form[key]}
                  onChange={e => setForm(prev => ({ ...prev, [key]: +e.target.value }))} />
                <div className="text-[0.65rem] text-white/20 mt-0.5">{t.optimal}: {p.optimal}</div>
              </div>
            );
          })}
        </div>
        <div className="mt-5">
          <button className="btn-primary" onClick={submit} disabled={loading}>
            {loading ? <span className="w-4 h-4 border-2 border-white/30 border-t-white rounded-full animate-spin-slow" /> : '🧪'}
            {loading ? t.analyzing : t.analyzeBtn}
          </button>
        </div>
      </div>

      {/* Results */}
      <AnimatePresence>
        {result && (
          <motion.div initial={{ opacity:0, y:20 }} animate={{ opacity:1, y:0 }} className="space-y-4">
            <div className="card-gradient rounded-2xl p-6">
              <div className="flex items-center justify-between mb-5 flex-wrap gap-3">
                <h2 className="font-display text-xl font-bold text-white/80">📊 {t.reportTitle}</h2>

                {/* ── DOWNLOAD BUTTON — direct PDF, no popup ── */}
                <motion.button
                  whileHover={{ scale:1.03 }} whileTap={{ scale:0.97 }}
                  onClick={handleDownload}
                  disabled={pdfLoading}
                  className="flex items-center gap-2 text-sm font-semibold px-4 py-2 rounded-xl transition-all bg-green-600 hover:bg-green-700 text-white border border-green-700 disabled:opacity-60 disabled:cursor-not-allowed shadow-lg shadow-green-900/30"
                >
                  {pdfLoading
                    ? <><Loader2 className="w-4 h-4 animate-spin" /> {t.downloading}</>
                    : <><Download className="w-4 h-4" /> {t.downloadReport}</>
                  }
                </motion.button>
              </div>

              <div className="flex flex-col md:flex-row gap-6 items-center">
                <div className="flex-shrink-0 text-center">
                  <div className="score-circle mx-auto" style={{ '--pct':`${result.score}%` }}>
                    <div className="relative z-10 text-center">
                      <div className="font-mono font-bold text-3xl text-gradient-green">{result.score}</div>
                      <div className="text-white/40 text-xs">/100</div>
                    </div>
                  </div>
                  <div className="mt-2">
                    <span className="font-bold text-lg text-white">{result.grade}</span>
                    <div className="text-sm text-white/50">{result.rating}</div>
                  </div>
                  <div className="mt-2">
                    <span className="text-[0.65rem] font-semibold px-2.5 py-1 rounded-full"
                      style={{ background:'rgba(20,92,30,0.3)', border:'1px solid rgba(74,222,128,0.25)', color:'#86efac' }}>
                      🌍 {getSoilLabel(soilType)}
                    </span>
                  </div>
                </div>
                <div className="flex-1 h-56 w-full">
                  <ResponsiveContainer width="100%" height="100%">
                    <RadarChart data={radarData}>
                      <PolarGrid stroke="rgba(255,255,255,0.08)" />
                      <PolarAngleAxis dataKey="subject" tick={{ fill:'rgba(255,255,255,0.4)', fontSize:11 }} />
                      <Radar name="Score" dataKey="score" stroke="#22c55e" fill="#22c55e" fillOpacity={0.15} strokeWidth={2} />
                    </RadarChart>
                  </ResponsiveContainer>
                </div>
                <div className="flex-1 space-y-2">
                  {PARAM_KEYS.map(key => {
                    const param    = result.parameters?.[key];
                    const statusTx = t.statusLabel?.[param?.status] || param?.status?.replace('_',' ') || '';
                    return (
                      <div key={key} className="flex items-center gap-2">
                        <span className="text-white/40 text-xs w-24 shrink-0 truncate">{t.params[key]?.label?.split(' ')[0]}</span>
                        <div className="flex-1 h-1.5 bg-white/10 rounded-full overflow-hidden">
                          <motion.div className="h-full rounded-full bg-gradient-to-r from-green-700 to-green-400"
                            initial={{ width:0 }}
                            animate={{ width:`${(param?.score || 0) / (param?.maxScore || 1) * 100}%` }}
                            transition={{ duration:0.8, delay:0.2 }} />
                        </div>
                        <span className={`text-xs font-mono w-16 text-right ${STATUS_STYLE[param?.status] || 'text-white/40'}`}>
                          {param?.value} {t.params[key]?.unit}
                        </span>
                        <span className={`text-[0.6rem] w-20 text-right ${STATUS_STYLE[param?.status] || 'text-white/30'}`}>
                          {statusTx}
                        </span>
                      </div>
                    );
                  })}
                </div>
              </div>
            </div>

            {result.recommendations?.length > 0 && (
              <div className="card-gradient rounded-2xl p-5">
                <h3 className="font-display text-lg font-bold text-white/80 mb-3">💡 {t.recommendations}</h3>
                <div className="space-y-2">
                  {result.recommendations.map((r, i) => (
                    <div key={i} className={`border rounded-lg p-3 text-sm flex items-start gap-2 ${ALERT_STYLE[r.type] || ALERT_STYLE.info}`}>
                      <span className="text-base mt-0.5">{r.type==='success'?'✅':r.type==='danger'?'🔴':r.type==='warning'?'⚠️':'ℹ️'}</span>
                      <span>{r.text}</span>
                    </div>
                  ))}
                </div>
              </div>
            )}

            <div className="card-gradient rounded-2xl p-5 border border-amber-500/10">
              <h3 className="font-display text-lg font-bold text-amber-400 mb-4">📋 {t.fertSchedule}</h3>
              <div className="grid sm:grid-cols-2 gap-4">
                {Object.entries(result.fertSchedule || {}).map(([crop, sched]) => (
                  <div key={crop} className="glass rounded-xl p-4">
                    <div className="font-semibold text-white text-sm capitalize mb-2">🌾 {crop}</div>
                    {Object.entries(sched).map(([k, v]) => (
                      <div key={k} className="text-xs text-white/50 mb-1">
                        <span className="text-white/30 capitalize">{k.replace(/([A-Z])/g,' $1')}: </span>{v}
                      </div>
                    ))}
                  </div>
                ))}
              </div>
            </div>
          </motion.div>
        )}
      </AnimatePresence>
    </div>
  );
}